cloud:
  aws:
    credentials:
      profileName:
      instanceProfile: false
    region:
      auto: false
      static: ap-northeast-1

amazon:
  region: ap-northeast-1
  dynamodb:
    endpoint: https://dynamodb.ap-northeast-1.amazonaws.com
    table: ma-furutanito-runner-status
  ecs:
    cluster: ma-furutanito-cluster
    taskDefinition: ma-furutanito-load-test
    containerName: ma-furutanito-load-test
    subnetIds: subnet-02fb5c9a3dceb48c1,subnet-0e4f80cf9f14633fb,subnet-0c0846166e3f8600f
    securityGroup: sg-0fc69388b99eb3893
  s3:
    bucketName: ma-furutanito-bucket
  sqs:
    endpoint: https://sqs.ap-northeast-1.amazonaws.com/
    queueName: ma-furutanito-queue

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
        internal:
          InstanceMetadataServiceResourceFetcher: error