package org.maca.continuous.perftest.domain.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;
import org.springframework.data.annotation.Id;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

@AllArgsConstructor
@NoArgsConstructor
@Builder
@Data
@DynamoDBTable(tableName = "runner-status")
public class RunnerStatus implements Serializable {
    @Id
    @Getter(AccessLevel.NONE)
    @Setter(AccessLevel.NONE)
    private PrimaryKey primaryKey;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String testId;
    @DynamoDBAttribute
    private String scenarioName;
    @DynamoDBAttribute
    private String clusterSize;
    @DynamoDBRangeKey
    private Date startTime;
    @DynamoDBAttribute
    private Date endTime;
    @DynamoDBAttribute
    private String status;
    @DynamoDBAttribute
    private String criteria;
    @DynamoDBAttribute
    private String result;
    @DynamoDBAttribute
    private String errorReason;
    @DynamoDBAttribute
    private List<String> completeTasks;

}
