package org.maca.continuous.perftest.domain.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

@AllArgsConstructor
@NoArgsConstructor
@Builder
@Data
@DynamoDBTable(tableName = "ma-furutanito-runner-status")
public class RunnerStatus implements Serializable {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String testId;
    @DynamoDBAttribute
    private String scenarioName;
    @DynamoDBAttribute
    private String clusterSize;
    @DynamoDBAttribute
    private Date startTime;
    @DynamoDBAttribute
    private Date endTime;
    @DynamoDBAttribute
    private String status;
    @DynamoDBAttribute
    private String result;
    @DynamoDBAttribute
    private String errorReason;
    @DynamoDBAttribute
    private List<String> completeTasks;

}
