spring:
  profiles:
    active: dev

cloud:
  aws:
    stack:
      auto: false

bucket:
  name: ma-furutanito-bucket
amazon:
  dynamodb:
    region: ap-northeast-1
    endpoint: https://dynamodb.ap-northeast-1.amazonaws.com
