AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template

# ------------------------------------------------------------#
# Input Parameters
# ------------------------------------------------------------#
Parameters:
  Prefix:
    Description: Prefix Name
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: ^[a-zA-Z][-a-zA-Z0-9]*$
    Default: continuous-perftest
  VPCCiderBlock:
    Description: CiderBlock paramater for VPC
    Type: String
    MinLength: 9
    MaxLength: 18
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    Default: 10.0.1.0/24
  VPCId:
    Description: VPC ID
    Type: AWS::EC2::VPC::Id
    Default: vpc

Resources:
# ------------------------------------------------------------#
# Nested Stack
# ------------------------------------------------------------#
  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./network.yaml
      Parameters:
        VPCId: !Ref VPCId
        VPCCiderBlock: !Ref VPCCiderBlock
        Prefix: !Ref Prefix

  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./s3.yaml
      Parameters:
        Prefix: !Ref Prefix

  # SQSStack:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: ./sqs.yaml

  # DynamoDBStack:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: ./dynamodb.yaml
  #     Parameters:
  #       Prefix: !Ref Prefix

  # ECSClusterStack:
  #   Type: AWS::CloudFormation::Stack
  #   DependsOn: NetworkStack
  #   Properties:
  #     TemplateURL: ./ecs-cluster.yaml

  # ECSTaskDefinitionStack:
  #   Type: AWS::CloudFormation::Stack
  #   DependsOn:
  #     - ECSClusterStack
  #   Properties:
  #     TemplateURL: ./ecs-task.yaml

  # ECSTaskRoleStack:
  #   Type: AWS::CloudFormation::Stack
  #   DependsOn:
  #     - ECSClusterStack
  #   Properties:
  #     TemplateURL: ./ecs-taskrole.yaml

  # ECSServiceStagingStack:
  #   Type: AWS::CloudFormation::Stack
  #   DependsOn:
  #     - ECSClusterStack
  #     - ECSTaskDefinitionStack
  #     - ECSTaskRoleStack
  #   Properties:
  #     TemplateURL: ./ecs-service.yaml
