AWSTemplateFormatVersion: '2010-09-09'
Description: DynamoDB Definition depends on network.yaml

Parameters:
  Prefix:
    Description: Prefix Name
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: ^[a-zA-Z][-a-zA-Z0-9]*$
    Default: continuous-perftest

Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${Prefix}-runner-status
      BillingMode: PROVISIONED
      SSESpecification: !Ref "AWS::NoValue"
      KeySchema:
        - AttributeName: testId
          KeyType: HASH
        - AttributeName: startTime
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: testId
          AttributeType: S
        - AttributeName: startTime
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  DynamoDBTable:
    Description: DynamoDB Table
    Value: !Ref DynamoDBTable
    Export:
      Name: !Sub ${Prefix}-Table