AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Task Definition

Parameters:
  Prefix:
    Description: Prefix Name
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: ^[a-zA-Z][-a-zA-Z0-9]*$
    Default: continuous-perftest
  ConsumerContainerImage:
    Description: Prefix Name
    Type: String
    MinLength: 1
    Default: repository/name:tag
  LoadContainerImage:
    Description: Prefix Name
    Type: String
    MinLength: 1
    Default: repository/name:tag

Resources:
  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: !Sub ${Prefix}-ECSTaskExecutionRole
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
        - arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess
        - arn:aws:iam::aws:policy/SecretsManagerReadWrite

  ConsumerECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${Prefix}-consumer
      RequiresCompatibilities:
        - EC2
      Memory: 1024
      Cpu: 512
      NetworkMode: bridge
      ExecutionRoleArn: !GetAtt ECSTaskExecutionRole.Arn
      TaskRoleArn:
        Fn::ImportValue: !Sub ${Prefix}-ECSTaskRole
      ContainerDefinitions:
        - Name: !Sub ${Prefix}-consumer
          Image: !Ref ConsumerContainerImage
          Memory: 1024
          Environment:
            - Name: ECS_CLUSTER
              Value:
                Fn::ImportValue: !Sub ${Prefix}-EcsCluster
            - Name: TASK_DEFINITION
              Value: !Sub ${Prefix}-load-test
            - Name: CONTAINER_NAME
              Value: !Sub ${Prefix}-load-test
            - Name: SUBNET_ID
              Value: !Sub
                - ${subnet1},${subnet2},${subnet3}
                - subnet1:  {'Fn::ImportValue': !Sub '${Prefix}-PrivateSubnet1'}
                  subnet2:  {'Fn::ImportValue': !Sub '${Prefix}-PrivateSubnet2'}
                  subnet3:  {'Fn::ImportValue': !Sub '${Prefix}-PrivateSubnet3'}
            - Name: SECURITY_GROUP
              Value:
                Fn::ImportValue: !Sub ${Prefix}-EcsClusterSg

  LoadECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${Prefix}-load-test
      RequiresCompatibilities:
        - FARGATE
        - EC2
      Memory: 1024
      Cpu: 512
      NetworkMode: awsvpc
      ExecutionRoleArn: !GetAtt ECSTaskExecutionRole.Arn
      TaskRoleArn:
        Fn::ImportValue: !Sub ${Prefix}-ECSTaskRole
      ContainerDefinitions:
        - Name: !Sub ${Prefix}-load-test
          Image: !Ref LoadContainerImage
          Memory: 1024
          Environment:
            - Name: S3_BUCKET
              Value: !Sub ${Prefix}-bucket

Outputs:
  ConsumerECSTaskDefinition:
    Description:  ECS Task Definition
    Value: !Ref ConsumerECSTaskDefinition
    Export:
      Name: !Sub ${Prefix}-ConsumerECSTaskDefinition
